name: CI

on: [pull_request]

jobs:
  unit_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependancies
        working-directory: ./packages/backend
        run: npm install
      - name: Run tests
        working-directory: ./packages/backend
        run: npm run test
      - name: Test build
        working-directory: ./packages/backend
        run: npm run build
